language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
script:
- bash build.sh
after_success:
- codecov
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
env:
  global:
  - secure: fMlA0MBQCob7xiPAliYBASnjeikGW1WgJfBzWUazeC+Q4xS0EhuShVd4x5b/yVlL9NFXBWF9NO+Ff/jjavf91UF2T8CEwCdbbXxFpVZ9qfvuKXWVBXh1K6bs9ZrQ4cv+DTl8n+CJeXK8ZS6iNf6PycF4i51+U8+fBTIinPFnV80sPfghBsbnzNOkkGHOX2BEeriebhsRaOEmAs+lEoeYLLNI2O5Fr2gd6boB1L1kXtHHuLR/Cm21ejFKjRX4RXCH0j/RzL341v/vcyQpetg15TtpWqIJ03c9R8LzhmyZQU5FVST1eN6ll2mdxvL5NKq39bnJEy5oAoeUftxm0N6kdTm4MFN1OpwKWE0R8NfaFSKqeSpjrP8xl04HRVky9FY/jV33dMxrlEXoQGK9ASXnDyCU7dTnSVuUQNqztbHt1cAT2oYU8nONby/+OzF3S3s3PgjaQFSHzOGKO07fpgiKwMLrIXIPIuZ1ZtNqwVd1m9NffnWH9n2nc7Y5+ADhrq1Z9pC/h2tuwgIlXgJpoBb9FwXyeQijoZJvzft/P68MXylEjhFlun+y3dyzrs/+KvliNx4kpE4A+kb0yq0xajF3MQM71deg0cqSFg5BX2KA5sWaR+Tpqs1qgNhyRwxyMkmUHEY9aDqd15qPpvw+YpRc+DNnwGPV2+//wQFhRhSGffY=
  - secure: NPtX9VF3dzgrahEDBXb0BHIwsiTA+gszvRBBjtjsFwkRvBQwY0nsHN4D571FAZ5WASCVLFYDDfN2x2Cxm0bOk33fX3/jA1jHp2OUWDZ9D2BiVNOauamgpH5gyEs4qhZGcmd8jr56Qq8ztTOFfejgFmCfMGQiKBC35VvkGz1TICBGjg4lwHXF6MIrJrJDKf7ugzHuAvaUhPPxyao7mvcKv+1lzoPpbXTHJdygJZ/3FaDTdkejGEecPEIioVILcwUVIUCUeKY166o13sUzZ3BSBjJCVtlACaJh+1olsO9mVQUgh4Anozm/8YB6JAR5tvc1V6xrlWEVjFc6j5nzNMtTCYwhhIoqqUOHmgHvT9qNELqNHECws2cC1LayE/wBcvxYGqYxJYFz/yWbQu60iSA164UGYjkNb6dzWZtYk3RHLZ/whBUyBVI81U0u9cpITcUAT8yHqtQ2em/kQW1gsmPt16URT+01lk/SJhMABGHt8dGCdrtLsRa11KUZjzU/yyDGENZ2H7jj18eGoqydALAJH0iaMBIoj2aeAkOov05lw/Jcl2sB9geA8MWzbZK7S87Udhe25DsyIi0HAgcv652A+05I2TejOnOwr0hgGbvXyTGRfdm/K7Z3yM+ZUOYWjua6V0XToMfNiRCsy4n8st1AJLd4PJtqkcfrJotDGcs8NHU=
