codecov:
  branch: master
  
coverage:
  project:
    RxAssertions:  # you can create many custom statuses
      precision: 2
      round: down
      range: 70...100
      paths:
        - "rx2assertj"
        target: 90%
    Rx2Assertions:
      paths:
        - "rxassertj"
      target: auto
